style: add styles to homepage
fridaland/InTheFight pull request #22
Opened 2020-10-22 16:21 UTC by connerdodge

Addresses issue #21 

Adds homepage Title and Description styles

2020-10-23 19:08 UTC, fridaland requested changes
@connerdodge this is looking great! 
Perhaps it wasn't totally clear on the issue- but would you mind adjusting the container for the headline and description to match the mockup below? 
![Screen Shot 2020-10-23 at 2 05 31 PM](https://user-images.githubusercontent.com/40510669/97044011-feac7900-1538-11eb-8f46-8088d193a1d2.png)
The only thing that seems to be missing is floating the elements as pictured above.

2020-10-23 19:48 UTC, connerdodge commented
@fridaland Let me know if the recent commit addresses the issue.

2020-10-24 02:17 UTC, fridaland requested changes
Just one small comment on the description width, otherwise this looks great!

2020-10-24 02:17 UTC, fridaland commented on src/styles/index.css
> +    max-width: 450px;
It would be good to increase the width a bit on the description
```suggestion
    width: 800px;
```

2020-10-28 13:54 UTC, fridaland approved these changes
Beautiful!

2020-10-28 18:44 UTC, merged